name: Close inactive issues
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  close-issues:
    if: github.repository_owner == 'kuadrant'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v5
        with:
          days-before-issue-stale: 30
          days-before-issue-close: 30
          stale-issue-label: "stale"
          stale-issue-message: "This issue is stale because it has been open for 30 days with no activity."
          stale-pr-message: "This PR is stale because it has been open for 30 days with no activity."
          close-issue-message: "This issue was closed because it has been inactive for 30 days since being marked as stale."
          close-pr-message: "This PR was closed because it has been inactive for 30 days since being marked as stale."
          days-before-pr-stale: 30
          days-before-pr-close: 30
          repo-token: ${{ secrets.STALE_CLOSER_GITHUB_TOKEN }}